name: Amazon Music YouTube Playlist Sync

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Ruby script
        run: ruby app.rb
        env:
          AMAZON_EMAIL: ${{ secrets.AMAZON_EMAIL }}
          AMAZON_PASSWORD: ${{ secrets.AMAZON_PASSWORD }}
          AMAZON_PLAYLIST_ID: ${{ secrets.AMAZON_PLAYLIST_ID }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
